/*

 SAMPLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\M\Documents\GitHub\Sepulture\assets\sprites\gbr\basicbackgrounds.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __samplemap_h_INCLUDE
#define __samplemap_h_INCLUDE

#define samplemapWidth 40
#define samplemapHeight 18
#define samplemapBank 0

extern const unsigned char samplemap[];

#endif

/* End of SAMPLEMAP.H */
