/*

 SMILEY_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char smileysprite[] =
{
  0x7E,0x7E,0xFF,0x81,0xDF,0xA1,0xD3,0xAD,
  0xFF,0x81,0xDB,0xA5,0xE7,0x99,0x7E,0x7E,
  0x7E,0x7E,0xFF,0x81,0xDB,0xA5,0xDB,0xA5,
  0xFF,0x81,0xC3,0xBD,0xF3,0x8D,0x7E,0x7E
};

/* End of SMILEY_SPRITE.C */
